# Generated by Django 4.2.7 on 2025-06-13 15:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('regular', 'Regular Token'), ('mail', 'Mail Token')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('subscription', 'Subscription Credit')], max_length=15)),
                ('action_type', models.CharField(blank=True, choices=[('postcard_send', 'Postcard Send'), ('email_send', 'Email Send'), ('sms_send', 'SMS Send'), ('phone_verification', 'Phone Verification'), ('address_verification', 'Address Verification'), ('property_lookup', 'Property Lookup'), ('lead_export', 'Lead Export'), ('api_call', 'API Call'), ('other', 'Other')], max_length=25, null=True)),
                ('tokens_before', models.IntegerField()),
                ('tokens_changed', models.IntegerField()),
                ('tokens_after', models.IntegerField()),
                ('cost_per_token', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'token_type'], name='core_tokent_user_id_4423ff_idx'), models.Index(fields=['transaction_type', 'created_at'], name='core_tokent_transac_35fcd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('analyzing', 'Analyzing'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'In Negotiation'), ('approved', 'Approved'), ('funded', 'Funded'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='identified', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('requested_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ltv_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.08'), max_digits=5)),
                ('term_months', models.IntegerField(default=24)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('property_inspection_completed', models.BooleanField(default=False)),
                ('title_search_completed', models.BooleanField(default=False)),
                ('financial_verification_completed', models.BooleanField(default=False)),
                ('projected_funding_date', models.DateField(blank=True, null=True)),
                ('tlc_opportunity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_to_tlc', models.BooleanField(default=False)),
                ('tlc_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='core.lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'user'], name='core_opport_status_5c7124_idx'), models.Index(fields=['ltv_ratio'], name='core_opport_ltv_rat_094ed4_idx'), models.Index(fields=['requested_loan_amount'], name='core_opport_request_668b56_idx')],
            },
        ),
    ]
