# Generated by Django 4.2.7 on 2025-06-20 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tokentransaction_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Browser')], max_length=50)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Accepted'), (4, 'On Hold'), (8, 'Closed'), (16, 'Declined'), (32, 'Declined - Safety'), (64, 'Hold Expired'), (128, 'Closed for Inactivity'), (256, 'Suspended'), (1024, 'Paused')], default=1)),
                ('lat_created', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('lng_created', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('lat_completed', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('lng_completed', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_with', models.CharField(blank=True, max_length=100, null=True)),
                ('link_type', models.CharField(blank=True, choices=[('USER', 'User'), ('OPPORTUNITY', 'Opportunity')], max_length=20, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('go_to_lead', models.BooleanField(default=False)),
                ('purchase_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('initial_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_on_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionDeclineReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('is_safety_related', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'reason'],
            },
        ),
        migrations.CreateModel(
            name='MissionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (4, 'Completed')], default=1)),
                ('optimization_url', models.TextField(blank=True, null=True)),
                ('is_optimized', models.BooleanField(default=False)),
                ('total_distance_meters', models.IntegerField(blank=True, null=True)),
                ('total_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mission_photos/')),
                ('lat', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('is_valid_location', models.BooleanField(default=False)),
                ('distance_from_target', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('radius', models.IntegerField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('amount_due_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_due_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='decline_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.missiondeclinereason'),
        ),
        migrations.AddField(
            model_name='mission',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.lead'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MissionRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('provided_index', models.IntegerField()),
                ('optimized_index', models.IntegerField(blank=True, null=True)),
                ('length_in_meters', models.IntegerField(blank=True, null=True)),
                ('travel_time_in_seconds', models.IntegerField(blank=True, null=True)),
                ('points', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Visited'), (4, 'Skipped')], default=1)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='core.missionroute')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='core.lead')),
            ],
            options={
                'ordering': ['optimized_index', 'provided_index'],
                'indexes': [models.Index(fields=['mission_route', 'optimized_index'], name='core_missio_mission_5a4f24_idx'), models.Index(fields=['prospect'], name='core_missio_prospec_1bfe96_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['user', 'status'], name='core_missio_user_id_c9e01b_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['prospect'], name='core_missio_prospec_c6d83d_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status', 'created_at'], name='core_missio_status_0893ca_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_ongoing'], name='core_missio_is_ongo_97891d_idx'),
        ),
    ]
