# Generated by Django 4.2.7 on 2025-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_mission_missiondeclinereason_missionroute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='mailing_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
