# Generated by Django 4.2.7 on 2025-06-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_subscriptionplan_usersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLCClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('lead', 'Lead'), ('applicant', 'Applicant'), ('client', 'Client'), ('inactive', 'Inactive')], default='prospect', max_length=20)),
                ('workflow_stage', models.CharField(choices=[('initial_contact', 'Initial Contact'), ('qualification', 'Qualification'), ('application_review', 'Application Review'), ('underwriting', 'Underwriting'), ('loan_approval', 'Loan Approval'), ('funding', 'Funding'), ('servicing', 'Loan Servicing')], default='initial_contact', max_length=30)),
                ('lead_source', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TLCTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('tax_year', models.IntegerField()),
                ('original_tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalties_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attorney_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_sale_date', models.DateField(blank=True, null=True)),
                ('lawsuit_status', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_info', to='core.tlcclient')),
            ],
        ),
        migrations.CreateModel(
            name='TLCPropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_land_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assessed_improvement_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assessed_total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_land_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_improvement_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_valuation', to='core.tlcclient')),
            ],
        ),
        migrations.CreateModel(
            name='TLCLoanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_to_value_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('funded', 'Funded'), ('declined', 'Declined'), ('paid_off', 'Paid Off')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('funding_date', models.DateTimeField(blank=True, null=True)),
                ('payoff_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_info', to='core.tlcclient')),
            ],
        ),
        migrations.CreateModel(
            name='TLCImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_clients', models.IntegerField(default=0)),
                ('invalid_emails', models.IntegerField(default=0)),
                ('missing_required_fields', models.IntegerField(default=0)),
                ('invalid_tax_amounts', models.IntegerField(default=0)),
                ('invalid_dates', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tlc_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TLCImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('raw_data', models.TextField()),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.tlcimportjob')),
            ],
        ),
        migrations.CreateModel(
            name='TLCClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('document', 'Document')], default='general', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.tlcclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TLCClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('mailing', 'Mailing Address'), ('property', 'Property Address')], max_length=20)),
                ('street_1', models.CharField(max_length=255)),
                ('street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.tlcclient')),
            ],
        ),
        migrations.AddIndex(
            model_name='tlcclient',
            index=models.Index(fields=['client_number'], name='core_tlccli_client__56e1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tlcclient',
            index=models.Index(fields=['status'], name='core_tlccli_status_36dcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='tlcclient',
            index=models.Index(fields=['workflow_stage'], name='core_tlccli_workflo_fb73ab_idx'),
        ),
        migrations.AddIndex(
            model_name='tlcclient',
            index=models.Index(fields=['created_at'], name='core_tlccli_created_c7beff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tlcclientaddress',
            unique_together={('client', 'address_type')},
        ),
    ]
