# Generated by Django 4.2.7 on 2025-06-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_campaign_userprofile_allowed_counties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('proposal', 'Proposal'), ('report', 'Report'), ('template', 'Template'), ('legal', 'Legal Document'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('tax_document', 'Tax Document'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('signed', 'Signed'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('version_notes', models.TextField(blank=True)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False)),
                ('template_variables', models.JSONField(blank=True, default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_merged', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.documentfolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_type', models.CharField(max_length=50)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_config', to='core.document')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('comment', 'View and Comment'), ('edit', 'Edit'), ('admin', 'Full Access')], default='view', max_length=10)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.document')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('admin', 'Full Access')], default='view', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.documentfolder')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_folder_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='shared_with',
            field=models.ManyToManyField(related_name='accessible_folders', through='core.DocumentFolderPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.document')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.documentcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Document Created'), ('updated', 'Document Updated'), ('viewed', 'Document Viewed'), ('downloaded', 'Document Downloaded'), ('shared', 'Document Shared'), ('commented', 'Comment Added'), ('signed', 'Document Signed'), ('status_changed', 'Status Changed'), ('version_created', 'New Version Created'), ('merged', 'Document Merged'), ('deleted', 'Document Deleted')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.documentfolder'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_leads',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.lead'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_missions',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.mission'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_properties',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.property'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_tlc_clients',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.tlcclient'),
        ),
        migrations.AddField(
            model_name='document',
            name='merged_from',
            field=models.ManyToManyField(blank=True, related_name='merged_into', to='core.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(related_name='accessible_documents', through='core.DocumentPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('signed', 'Signed'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('signed', 'Signed'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('workflow_step', models.CharField(blank=True, max_length=50)),
                ('approval_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document'], name='core_docume_documen_8e92e6_idx'), models.Index(fields=['created_at'], name='core_docume_created_f13ec6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['parent'], name='core_docume_parent__ce67c1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['created_by'], name='core_docume_created_8c7926_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfolder',
            unique_together={('parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['document'], name='core_docume_documen_0b0127_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['user'], name='core_docume_user_id_fddcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['is_resolved'], name='core_docume_is_reso_b5436f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['document'], name='core_docume_documen_52a8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['activity_type'], name='core_docume_activit_c1d9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['user'], name='core_docume_user_id_d3fa97_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['created_at'], name='core_docume_created_499c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='core_docume_documen_5649ee_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='core_docume_status_daedd3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder'], name='core_docume_folder__032807_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='core_docume_created_6e65fe_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_template'], name='core_docume_is_temp_991665_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_shared'], name='core_docume_is_shar_613a83_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='core_docume_created_f1aada_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['updated_at'], name='core_docume_updated_c0378f_idx'),
        ),
    ]
