name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 134.199.192.164
        username: droneuser
        password: ${{ secrets.DO_SERVER_PASSWORD }}
        timeout: 300s
        command_timeout: 600s
        script: |
          cd /home/droneuser/dronestrike-v2
          git fetch origin main
          git stash push -m "Auto-stash before deployment" || true
          git clean -fd || true
          git pull origin main
          
          # Backend deployment
          cd django_backend
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          pkill -f "manage.py runserver" || true
          nohup python manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &
          
          # Frontend deployment  
          cd ../frontend
          npm install --no-audit --production=false
          npm run build
          sudo cp -r build/* /var/www/dronestrike-v2/
          sudo systemctl restart nginx
          
          echo "Deployment completed successfully"