name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Update Code
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 134.199.192.164
        username: droneuser
        password: ${{ secrets.DO_SERVER_PASSWORD }}
        timeout: 60s
        script: |
          cd /home/droneuser/dronestrike-v2
          git fetch origin main
          git stash push -m "Auto-stash before deployment" || true
          git clean -fd || true
          git pull origin main
          echo "Code updated successfully"
          
          # Start frontend build in background
          cd frontend
          nohup npm ci --silent > npm-install.log 2>&1 && nohup npm run build --silent > build.log 2>&1 &
          echo "Frontend build started in background"
    
    - name: Deploy Backend
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 134.199.192.164
        username: droneuser
        password: ${{ secrets.DO_SERVER_PASSWORD }}
        timeout: 45s
        script: |
          cd /home/droneuser/dronestrike-v2/django_backend
          source venv/bin/activate
          python manage.py migrate --noinput || true
          pkill -f "manage.py runserver" || true
          nohup python manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &
          sleep 1
          echo "Backend restarted successfully"
    
    - name: Deploy Frontend
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 134.199.192.164
        username: droneuser
        password: ${{ secrets.DO_SERVER_PASSWORD }}
        timeout: 60s
        script: |
          cd /home/droneuser/dronestrike-v2/frontend
          if [ -d "build" ]; then
            echo "dronestrike-v2-prod.XGT13ds" | sudo -S cp -r build/* /var/www/dronestrike-v2/ || true
            echo "dronestrike-v2-prod.XGT13ds" | sudo -S systemctl restart nginx || true
            echo "Frontend deployed successfully"
          else
            echo "No build directory found, skipping frontend deployment"
          fi