name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy Application
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 134.199.192.164
        username: droneuser
        password: ${{ secrets.DO_SERVER_PASSWORD }}
        timeout: 30s
        script: |
          cd /home/droneuser/dronestrike-v2
          chmod +x deploy.sh
          echo "dronestrike-v2-prod.XGT13ds" | sudo -S ./deploy.sh