# All 254 Texas Counties with their major cities
ALL_TEXAS_COUNTIES = {
    'Anderson': ['Palestine', 'Elkhart', 'Frankston'],
    'Andrews': ['Andrews'],
    'Angelina': ['Lufkin', 'Huntington', 'Diboll'],
    'Aransas': ['Rockport', 'Fulton'],
    'Archer': ['Archer City', 'Scotland'],
    'Armstrong': ['Claude'],
    'Atascosa': ['Jourdanton', 'Pleasanton', 'Poteet'],
    'Austin': ['Bellville', 'Sealy', 'Wallis'],
    'Bailey': ['Muleshoe'],
    'Bandera': ['Bandera'],
    'Bastrop': ['Bastrop', 'Elgin', 'Smithville'],
    'Baylor': ['Seymour'],
    'Bee': ['Beeville', 'Skidmore'],
    'Bell': ['Killeen', 'Temple', 'Belton', 'Harker Heights'],
    'Bexar': ['San Antonio', 'Schertz', 'Universal City', 'Converse', 'Live Oak'],
    'Blanco': ['Johnson City', 'Blanco'],
    'Borden': ['Gail'],
    'Bosque': ['Meridian', 'Clifton'],
    'Bowie': ['Texarkana', 'Marshall', 'De Kalb'],
    'Brazoria': ['Pearland', 'Lake Jackson', 'Angleton', 'Clute', 'Freeport'],
    'Brazos': ['College Station', 'Bryan'],
    'Brewster': ['Alpine'],
    'Briscoe': ['Silverton'],
    'Brooks': ['Falfurrias'],
    'Brown': ['Brownwood'],
    'Burleson': ['Caldwell', 'Somerville'],
    'Burnet': ['Burnet', 'Marble Falls'],
    'Caldwell': ['Lockhart', 'Luling'],
    'Calhoun': ['Port Lavaca', 'Point Comfort'],
    'Callahan': ['Baird', 'Clyde'],
    'Cameron': ['Brownsville', 'Harlingen', 'San Benito', 'Port Isabel'],
    'Camp': ['Pittsburg'],
    'Carson': ['Panhandle'],
    'Cass': ['Marshall', 'Atlanta', 'Hughes Springs'],
    'Castro': ['Dimmitt'],
    'Chambers': ['Anahuac', 'Mont Belvieu', 'Winnie'],
    'Cherokee': ['Jacksonville', 'Rusk'],
    'Childress': ['Childress'],
    'Clay': ['Henrietta'],
    'Cochran': ['Morton'],
    'Coke': ['Robert Lee'],
    'Coleman': ['Coleman', 'Santa Anna'],
    'Collin': ['Plano', 'McKinney', 'Frisco', 'Allen', 'Richardson'],
    'Collingsworth': ['Wellington'],
    'Colorado': ['Columbus', 'Eagle Lake'],
    'Comal': ['New Braunfels', 'Bulverde'],
    'Comanche': ['Comanche', 'De Leon'],
    'Concho': ['Paint Rock'],
    'Cooke': ['Gainesville', 'Muenster'],
    'Coryell': ['Killeen', 'Copperas Cove', 'Gatesville'],
    'Cottle': ['Paducah'],
    'Crane': ['Crane'],
    'Crockett': ['Ozona'],
    'Crosby': ['Crosbyton'],
    'Culberson': ['Van Horn'],
    'Dallam': ['Dalhart'],
    'Dallas': ['Dallas', 'Irving', 'Garland', 'Grand Prairie', 'Mesquite'],
    'Dawson': ['Lamesa'],
    'Deaf Smith': ['Hereford'],
    'Delta': ['Cooper'],
    'Denton': ['Denton', 'Lewisville', 'Flower Mound', 'Carrollton', 'The Colony'],
    'DeWitt': ['Cuero', 'Yoakum'],
    'Dickens': ['Dickens'],
    'Dimmit': ['Carrizo Springs'],
    'Donley': ['Clarendon'],
    'Duval': ['San Diego'],
    'Eastland': ['Eastland', 'Cisco'],
    'Ector': ['Odessa'],
    'Edwards': ['Rocksprings'],
    'Ellis': ['Waxahachie', 'Ennis', 'Midlothian'],
    'El Paso': ['El Paso'],
    'Erath': ['Stephenville', 'Dublin'],
    'Falls': ['Marlin'],
    'Fannin': ['Bonham', 'Honey Grove'],
    'Fayette': ['La Grange', 'Schulenburg'],
    'Fisher': ['Roby'],
    'Floyd': ['Floydada'],
    'Foard': ['Crowell'],
    'Fort Bend': ['Sugar Land', 'Missouri City', 'Rosenberg', 'Stafford'],
    'Franklin': ['Mount Vernon'],
    'Freestone': ['Fairfield'],
    'Frio': ['Dilley', 'Pearsall'],
    'Gaines': ['Seminole'],
    'Galveston': ['Galveston', 'League City', 'Texas City', 'Friendswood'],
    'Garza': ['Post'],
    'Gillespie': ['Fredericksburg'],
    'Glasscock': ['Garden City'],
    'Goliad': ['Goliad'],
    'Gonzales': ['Gonzales', 'Nixon'],
    'Gray': ['Pampa'],
    'Grayson': ['Sherman', 'Denison'],
    'Gregg': ['Longview', 'Kilgore'],
    'Grimes': ['Navasota', 'Anderson'],
    'Guadalupe': ['Seguin', 'Schertz'],
    'Hale': ['Plainview'],
    'Hall': ['Memphis'],
    'Hamilton': ['Hamilton'],
    'Hansford': ['Spearman'],
    'Hardeman': ['Quanah'],
    'Hardin': ['Kountze', 'Silsbee'],
    'Harris': ['Houston', 'Pasadena', 'Baytown', 'Sugar Land', 'Pearland'],
    'Harrison': ['Marshall', 'Longview'],
    'Hartley': ['Channing'],
    'Haskell': ['Haskell'],
    'Hays': ['San Marcos', 'Kyle', 'Buda'],
    'Hemphill': ['Canadian'],
    'Henderson': ['Athens'],
    'Hidalgo': ['McAllen', 'Edinburg', 'Mission', 'Pharr', 'Weslaco'],
    'Hill': ['Hillsboro'],
    'Hockley': ['Levelland'],
    'Hood': ['Granbury'],
    'Hopkins': ['Sulphur Springs'],
    'Houston': ['Crockett'],
    'Howard': ['Big Spring'],
    'Hudspeth': ['Sierra Blanca'],
    'Hunt': ['Greenville', 'Commerce'],
    'Hutchinson': ['Borger'],
    'Irion': ['Mertzon'],
    'Jack': ['Jacksboro'],
    'Jackson': ['Edna'],
    'Jasper': ['Jasper', 'Kirbyville'],
    'Jeff Davis': ['Fort Davis'],
    'Jefferson': ['Beaumont', 'Port Arthur', 'Nederland', 'Groves'],
    'Jim Hogg': ['Hebbronville'],
    'Jim Wells': ['Alice'],
    'Johnson': ['Cleburne', 'Burleson'],
    'Jones': ['Anson', 'Stamford'],
    'Karnes': ['Karnes City', 'Kenedy'],
    'Kaufman': ['Kaufman', 'Terrell'],
    'Kendall': ['Boerne'],
    'Kenedy': ['Sarita'],
    'Kent': ['Jayton'],
    'Kerr': ['Kerrville'],
    'Kimble': ['Junction'],
    'King': ['Guthrie'],
    'Kinney': ['Brackettville'],
    'Kleberg': ['Kingsville'],
    'Knox': ['Knox City'],
    'Lamar': ['Paris', 'Blossom'],
    'Lamb': ['Littlefield'],
    'Lampasas': ['Lampasas'],
    'La Salle': ['Cotulla'],
    'Lavaca': ['Hallettsville', 'Yoakum'],
    'Lee': ['Giddings'],
    'Leon': ['Centerville'],
    'Liberty': ['Liberty', 'Cleveland', 'Dayton'],
    'Limestone': ['Mexia', 'Groesbeck'],
    'Lipscomb': ['Lipscomb'],
    'Live Oak': ['George West'],
    'Llano': ['Llano'],
    'Loving': ['Mentone'],
    'Lubbock': ['Lubbock'],
    'Lynn': ['Tahoka'],
    'Madison': ['Madisonville'],
    'Marion': ['Jefferson'],
    'Martin': ['Stanton'],
    'Mason': ['Mason'],
    'Matagorda': ['Bay City', 'Palacios'],
    'Maverick': ['Eagle Pass'],
    'McCulloch': ['Brady'],
    'McLennan': ['Waco', 'Hewitt'],
    'McMullen': ['Tilden'],
    'Medina': ['Hondo', 'Castroville'],
    'Menard': ['Menard'],
    'Midland': ['Midland'],
    'Milam': ['Cameron', 'Rockdale'],
    'Mills': ['Goldthwaite'],
    'Mitchell': ['Colorado City'],
    'Montague': ['Montague', 'Nocona'],
    'Montgomery': ['Conroe', 'The Woodlands', 'Spring', 'Tomball'],
    'Moore': ['Dumas'],
    'Morris': ['Daingerfield'],
    'Motley': ['Matador'],
    'Nacogdoches': ['Nacogdoches'],
    'Navarro': ['Corsicana'],
    'Newton': ['Newton'],
    'Nolan': ['Sweetwater'],
    'Nueces': ['Corpus Christi', 'Robstown'],
    'Ochiltree': ['Perryton'],
    'Oldham': ['Vega'],
    'Orange': ['Orange', 'Vidor', 'Bridge City'],
    'Palo Pinto': ['Mineral Wells', 'Weatherford'],
    'Panola': ['Carthage', 'Marshall'],
    'Parker': ['Weatherford', 'Granbury'],
    'Parmer': ['Friona', 'Bovina'],
    'Pecos': ['Fort Stockton'],
    'Polk': ['Livingston'],
    'Potter': ['Amarillo'],
    'Presidio': ['Marfa', 'Presidio'],
    'Rains': ['Emory'],
    'Randall': ['Canyon'],
    'Reagan': ['Big Lake'],
    'Real': ['Leakey'],
    'Red River': ['Clarksville'],
    'Reeves': ['Pecos'],
    'Refugio': ['Refugio'],
    'Roberts': ['Miami'],
    'Robertson': ['Franklin', 'Hearne'],
    'Rockwall': ['Rockwall', 'Rowlett'],
    'Runnels': ['Ballinger'],
    'Rusk': ['Henderson', 'Kilgore'],
    'Sabine': ['Hemphill'],
    'San Augustine': ['San Augustine'],
    'San Jacinto': ['Coldspring'],
    'San Patricio': ['Sinton', 'Aransas Pass'],
    'San Saba': ['San Saba'],
    'Schleicher': ['Eldorado'],
    'Scurry': ['Snyder'],
    'Shackelford': ['Albany'],
    'Shelby': ['Center'],
    'Sherman': ['Stratford'],
    'Smith': ['Tyler', 'Whitehouse'],
    'Somervell': ['Glen Rose'],
    'Starr': ['Rio Grande City'],
    'Stephens': ['Breckenridge'],
    'Sterling': ['Sterling City'],
    'Stonewall': ['Aspermont'],
    'Sutton': ['Sonora'],
    'Swisher': ['Tulia'],
    'Tarrant': ['Fort Worth', 'Arlington', 'Mansfield', 'Euless', 'Bedford'],
    'Taylor': ['Abilene'],
    'Terrell': ['Sanderson'],
    'Terry': ['Brownfield'],
    'Throckmorton': ['Throckmorton'],
    'Titus': ['Mount Pleasant'],
    'Tom Green': ['San Angelo'],
    'Travis': ['Austin', 'Cedar Park', 'Pflugerville', 'Lago Vista', 'Bee Cave'],
    'Trinity': ['Groveton'],
    'Tyler': ['Woodville'],
    'Upshur': ['Gilmer', 'Big Sandy'],
    'Upton': ['Rankin'],
    'Uvalde': ['Uvalde'],
    'Val Verde': ['Del Rio'],
    'Van Zandt': ['Canton', 'Grand Saline'],
    'Victoria': ['Victoria'],
    'Walker': ['Huntsville'],
    'Waller': ['Hempstead', 'Prairie View'],
    'Ward': ['Monahans'],
    'Washington': ['Brenham'],
    'Webb': ['Laredo'],
    'Wharton': ['Wharton', 'El Campo'],
    'Wheeler': ['Wheeler'],
    'Wichita': ['Wichita Falls'],
    'Wilbarger': ['Vernon'],
    'Willacy': ['Raymondville'],
    'Williamson': ['Round Rock', 'Cedar Park', 'Georgetown', 'Leander'],
    'Wilson': ['Floresville'],
    'Winkler': ['Kermit'],
    'Wise': ['Decatur', 'Bridgeport'],
    'Wood': ['Quitman'],
    'Yoakum': ['Plains'],
    'Young': ['Graham'],
    'Zapata': ['Zapata'],
    'Zavala': ['Crystal City']
}